### ISSUE TITLE
Should you make the forms, TOC, Staff example link to the appropriate fourm motion li

### ISSUE THREAD

**Issue by Fluffy728** [tunderwood89/FireShop#4]
Should you make the forms, TOC, Staff example link to the appropriate fourm motion lino?

for example, forms gos to the form area in our fourm.

and staff would go to staff list topic

and TOC would go to TOC in important notices.

example. 

Will you do that?, @tunderwood89

**Comment by tunderwood89** [comment]
Oh yeah, that's a good idea! I'll make a link to that, in a sec.

**Comment by Fluffy728** [comment]
It is not compeleted

**Comment by tunderwood89** [comment]
> It is not compeleted

I'm on it, I'm on it!
