### ISSUE TITLE
Dev Update and a couple of polls!

### ISSUE THREAD

**Issue by tunderwood89** [tunderwood89/FireShop#7]
Hi everyone!
I am gonna move the wiki to GitBooks, it is so much easier to use.
Also, I have a question for you guys. Who is actually helping?
I have only seen commits from 3 people on the team:
@tunderwood89 
@Fluffy728 
@windowsmas 
Please work on this, or I will remove you as contributors.

Finally, I have a poll! Who would rather we just use a platform like bubble.io or another app/website builder?
[Vote here!](https://take.supersurvey.com/poll4843419x9bb44aeD-149)

**Comment by Fluffy728** [comment]
Done

**Comment by Fluffy728** [comment]
Done

**Comment by GlitchOfBugington** [comment]
> Hi everyone!
> I am gonna move the wiki to GitBooks, it is so much easier to use.
> Also, I have a question for you guys. Who is actually helping?
> I have only seen commits from 3 people on the team:
> @tunderwood89 
> @Fluffy728 
> @windowsmas 
> Please work on this, or I will remove you as contributors.
> 
> Finally, I have a poll! Who would rather we just use a platform like bubble.io or another app/website builder?
> [Vote here!](https://take.supersurvey.com/poll4843419x9bb44aeD-149)

I can do some tomorrow, although sprinkled due to external things.

**Comment by redstone-scratch** [comment]
I did the survey, also sorry for not contributing.

**Comment by tunderwood89** [comment]
> I did the survey, also sorry for not contributing.

Don't worry, I just needed a sign you were active!

**Comment by tunderwood89** [comment]
> > Hi everyone!
> > I am gonna move the wiki to GitBooks, it is so much easier to use.
> > Also, I have a question for you guys. Who is actually helping?
> > I have only seen commits from 3 people on the team:
> > @tunderwood89
> > @Fluffy728
> > @windowsmas
> > Please work on this, or I will remove you as contributors.
> > Finally, I have a poll! Who would rather we just use a platform like bubble.io or another app/website builder?
> > [Vote here!](https://take.supersurvey.com/poll4843419x9bb44aeD-149)
> 
> I can do some tomorrow, although sprinkled due to external things.

Ok!

**Comment by Fluffy728** [comment]
Quiz completed, so it is actually completed
